name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./dashboard
        env:
          VERCEL_ORG_ID: team_upKiRAOJ4yCIYRQvYwTGZ19q
          VERCEL_PROJECT_ID: prj_3dD1G1gnpWzwZ7AZ4L5vQjsrMiML
